# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the control plane in GitHub Actions    |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: Deploy Control Plane
run-name: Deploy Control Plane by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployer:
        default: MGMT-WEEU-DEP01-INFRASTRUCTURE
        description: "Deployer configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
        type: string
      library:
        default: MGMT-WEEU-SAP_LIBRARY
        description: "SAP Library configuration name, use the following syntax: ENV-LOCA-SAP_LIBRARY"
        type: string
      environment:
        default: MGMT
        description: Environment name, MGMT, DEV, QA, etc
        type: string
      use_webapp_param:
        default: true
        description: Deploy the configuration web application infrastructure
        type: boolean
      deploy_webapp_software:
        default: true
        description: "Deploy the configuration web application software"
        type: boolean
      use_deployer:
        default: false
        description: Run on self hosted agent
        type: boolean
      force_reset:
        default: false
        description: Force a re-install - may require multiple re-runs
        type: boolean

permissions:
  contents: write
  id-token: write

jobs:
  setup_deployer:
    environment: ${{ inputs.deployer }}
    name: Prepare the self hosted runners(s)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xpiritbv/azure-sap-automation:github-workflow
    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        #   sparse-checkout: |
        #     WORKSPACES

      # Required permissions: org level runner registration permissions
      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Setup deployer'
        run: |
          echo '${{ toJSON(github) }}' > /tmp/github_context.json
          deploy/automation/01-deploy-control-plane/01-setup-deployer.sh
        # TODO: working-directory: /source
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          APP_REGISTRATION_APP_ID: ${{ secrets.APP_REGISTRATION_APP_ID }}
          WEB_APP_CLIENT_SECRET: ${{ secrets.WEB_APP_CLIENT_SECRET }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          # GITHUB_CONTEXT: ${{ toJSON(github) }}
          TF_VAR_ansible_core_version: 2.15 # TODO: Need to be stored in App Configurations
          # TODO: connection_name: ${{ inputs.connection_name }}
          deployer_environment: ${{ inputs.environment }}
          deployerconfig: ${{ inputs.deployer }}.tfvars
          deployerfolder: ${{ inputs.deployer }}
          force_reset: ${{ inputs.force_reset }}
          libraryconfig: ${{ inputs.library }}.tfvars
          libraryfolder: ${{ inputs.library }}
          log: logfile_${{ github.run_number }}-${{ github.run_attempt }}
          tf_version: 1.6.2 # Latest version is already installed in the hosted agent
          use_webapp: ${{ inputs.use_webapp_param }}
          APP_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          RUNNER_GROUP: "Default"
          CONFIG_REPO_PATH: ${{ github.workspace }}/WORKSPACES
          SAP_AUTOMATION_REPO_PATH: ${{ github.workspace }} # TODO: Remove this line when using the sccripts from the container

  deploy_controlplane:
    name: Deploy the control plane
    needs: prepare_deployer
    runs-on: ubuntu-latest # or self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  web_app_deployment:
    if: ${{ inputs.use_webapp_param }} && ${{ inputs.deploy_webapp_software }}
    name: Deploy SAP configuration Web App
    needs: deploy_controlplane
    runs-on: ubuntu-latest # or self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
