# /*---------------------------------------------------------------------------8
# |                                                                            |
# |         This pipeline deploys the control plane in GitHub Actions          |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: Deploy Control Plane
run-name: Deploy Control Plane by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployer:
        description: "Deployer configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
        required: true
        type: environment
      library:
        default: MGMT-WEEU-SAP_LIBRARY
        description: "SAP Library configuration name, use the following syntax: ENV-LOCA-SAP_LIBRARY"
        type: choice
        options:
        - MGMT-WEEU-SAP_LIBRARY
      environment:
        default: MGMT
        description: Environment name, MGMT, DEV, QA, etc
        type: choice
        options:
        - MGMT
        - DEV
        - QA
        - PROD
      use_webapp:
        default: true
        description: Deploy the configuration web application infrastructure
        type: boolean
      deploy_webapp_software:
        default: true
        description: "Deploy the configuration web application software"
        type: boolean
      force_reset:
        default: false
        description: Force a re-install - may require multiple re-runs
        type: boolean

permissions:
  contents: write
  id-token: write

jobs:
  setup_deployer:
    name: Prepare the self hosted runners(s)
    environment: ${{ inputs.deployer }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xpiritbv/azure-sap-automation:github-workflow
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        #   sparse-checkout: |
        #     WORKSPACES

      # Required permissions: org level runner registration permissions
      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Set log level'
        id: log_level
        run: |
          #!/usr/bin/env bash
          log_level=WARN

          if [ ${{ secrets.ACTIONS_RUNNER_DEBUG }} == "true" ] || [ ${{ env.ACTIONS_RUNNER_DEBUG }} == "true" ]; then
            $log_level=DEBUG
          fi

          echo "{log_level}={$log_level}" >> $GITHUB_OUTPUT

      - name: Setup deployer
        run: |
          echo '${{ toJSON(github) }}' > /tmp/github_context.json
          deploy/automation/01-deploy-control-plane/01-setup-deployer.sh
        # TODO: working-directory: /source
        env:
          # TODO: connection_name: ${{ inputs.connection_name }}
          APP_REGISTRATION_APP_ID: ${{ secrets.APP_REGISTRATION_APP_ID }}
          APP_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          CONFIG_REPO_PATH: ${{ github.workspace }}/WORKSPACES
          RUNNER_GROUP: "Default"
          SAP_AUTOMATION_REPO_PATH: ${{ github.workspace }} # TODO: Remove this line when using the sccripts from the container
          TF_VAR_ansible_core_version: 2.15 # TODO: Need to be stored in App Configurations
          WEB_APP_CLIENT_SECRET: ${{ secrets.WEB_APP_CLIENT_SECRET }}
          deployer_environment: ${{ inputs.environment }}
          deployerconfig: ${{ inputs.deployer }}.tfvars
          deployerfolder: ${{ inputs.deployer }}
          force_reset: ${{ inputs.force_reset }}
          libraryconfig: ${{ inputs.library }}.tfvars
          libraryfolder: ${{ inputs.library }}
          TF_LOG: ${{ steps.log_level.outputs.log_level }}
          log: logfile_${{ github.run_number }}-${{ github.run_attempt }}
          tf_version: 1.6.2 # Latest version is already installed in the hosted agent
          use_webapp: ${{ inputs.use_webapp }}

      - uses: actions/upload-artifact@v4
        with:
          name: 'setup-deployer-logs-${{ github.run_number }}-${{ github.run_attempt }}'
          path: ${{ github.workspace }}/WORKSPACES/.sap_deployment_automation/terraform.log

  deploy_controlplane:
    name: Deploy the control plane
    environment: ${{ inputs.deployer }}
    needs: setup_deployer
    runs-on: self-hosted
    container:
      image: ghcr.io/xpiritbv/azure-sap-automation:github-workflow
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy control plane
        run: |
          echo '${{ toJSON(github) }}' > /tmp/github_context.json
          deploy/automation/01-deploy-control-plane/02-deploy-control-plane.sh
        # TODO: working-directory: /source
        env:
          APP_REGISTRATION_APP_ID: ${{ secrets.APP_REGISTRATION_APP_ID }}
          CONFIG_REPO_PATH: ${{ github.workspace }}/WORKSPACES
          CP_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CP_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          CP_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          CP_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          SAP_AUTOMATION_REPO_PATH: ${{ github.workspace }} # TODO: Remove this line when using the sccripts from the container
          WEB_APP_CLIENT_SECRET: ${{ secrets.WEB_APP_CLIENT_SECRET }}
          deployer_environment: ${{ inputs.environment }}
          deployerconfig: ${{ inputs.deployer }}.tfvars
          deployerfolder: ${{ inputs.deployer }}
          libraryconfig: ${{ inputs.library }}.tfvars
          libraryfolder: ${{ inputs.library }}
          use_webapp: ${{ inputs.use_webapp }}

  web_app_deployment:
    if: ${{ inputs.use_webapp }} && ${{ inputs.deploy_webapp_software }}
    name: Deploy SAP configuration Web App
    needs: deploy_controlplane
    runs-on: self-hosted
    container:
      image: ghcr.io/xpiritbv/azure-sap-automation:github-workflow
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
