name: Build
run-name: Build by @${{ github.actor }}

on:
  # TODO: On Push/PR?
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine tags
      id: meta
      run: |
        buildid=$(date +"%Y%U")
        run: echo "{tags}={buildid}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: "${{env.IMAGE_NAME}}:${{ steps.meta.outputs.tags }}"
